### PR TITLE
Welcome to Atlantis!

### PR DESCRIPTION
**Pull request by stuxnet78**
In this pull request we will learn how to use atlantis. There are various commands that are available to you:
* Start by typing `atlantis help` in the comments.
* Next, lets plan by typing `atlantis plan` in the comments. That will run a `terraform plan`.
* Now lets apply that plan. Type `atlantis apply` in the comments. This will run a `terraform apply`.

Thank you for trying out atlantis. For more info on running atlantis in production see https://github.com/hootsuite/atlantis

### CODE REVIEW

**Comment by manigandankec** [comment]
atlantis plan

**Comment by stuxnet78** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /tmp/atlantis/data/repos/stuxnet78/atlantis-example/1/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/tmp/atlantis/data/repos/stuxnet78/atlantis-example/1/default/default.tfplan"


```

* To **discard** this plan click [here](https://10890e04.ngrok.io/lock?id=stuxnet78%252Fatlantis-example%252F.%252Fdefault).

**Comment by stuxnet78** [comment]
Locks and plans deleted for the projects and environments modified in this pull request:

- path: `stuxnet78/atlantis-example/.` environment: `default`

**Comment by manigandankec** [comment]
atlantis apply

**Comment by stuxnet78** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by manigandankec** [comment]
atlantis apply

**Comment by stuxnet78** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by stuxnet78** [comment]
atlantis apply

**Comment by stuxnet78** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
